# Generated by Django 3.2.8 on 2022-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetrecord',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian')], default='en', max_length=2),
        ),
    ]
